import {services,specialties,companies,processSteps,homeFaqs} from './content.mjs';
import {escapeHtml as esc,icon,button,contact,faq,navLabel} from './layout.mjs';

function serviceVisual(kind) {
  if(kind==='GoHighLevel') return `<div class="crm-diagram" role="img" aria-label="An example CRM connecting forms, conversations and pipeline stages"><span class="diagram-tag">A place for every next step</span><div class="crm-node core">GHL<span>Your business, connected</span></div><div class="crm-branches"><span>Forms</span><span>Conversations</span><span>Pipeline</span></div></div>`;
  if(kind==='Automation') return `<div class="automation-diagram" role="img" aria-label="Example automation: inquiry, follow-up, team handoff"><div><span>1</span> A new inquiry <i>↗</i></div><div><span>2</span> A thoughtful follow-up <i>↗</i></div><div><span>3</span> The right handoff <i>✓</i></div></div>`;
  return `<div class="funnel-diagram" role="img" aria-label="Example funnel structure: your offer, a clear action, a next step"><span>Your offer</span><span>A clear action</span><span>The next step ${icon('right')}</span></div>`;
}

export function home(context){return `
<section class="hero wrap" aria-labelledby="hero-title"><div class="hero-layout"><div class="hero-copy"><h1 id="hero-title"><span class="hero-kicker"><span class="status-dot" aria-hidden="true"></span>GoHighLevel (GHL) expert</span> <span class="hero-line">Less manual.</span> <span class="hero-line hero-accent"><em>More momentum.</em></span></h1><p class="hero-lede">I’m <strong>Hanzla Amjad</strong>, a GoHighLevel expert connecting funnels, CRM and automation, so your business can move as smoothly as your ideas.</p><div class="hero-actions">${button('Let’s build something good','/#contact','magnetic')}<a class="quiet-link" href="#expertise"><span>Explore my expertise</span><span aria-hidden="true">↓</span></a></div></div><div class="flow-stage" role="img" aria-label="An animated three-dimensional funnel showing a path from capture through connection to conversion"><div class="flow-aura" aria-hidden="true"></div><canvas id="flow-canvas" aria-hidden="true"></canvas><div class="flow-fallback" aria-hidden="true"><span></span><span></span><span></span></div><div class="stage-node node-one" aria-hidden="true"><span class="node-index">1</span><span>Capture.</span></div><div class="stage-node node-two" aria-hidden="true"><span class="node-index">2</span><span>Connect.</span></div><div class="stage-node node-three" aria-hidden="true"><span class="node-index">3</span><span>Convert.</span></div></div></div><div class="hero-bottom"><a class="hero-person" href="#about"><img src="/assets/hanzla-avatar.jpg" width="52" height="52" alt="Hanzla Amjad"><span><strong>Available for new projects</strong><span>Remote · Based in Pakistan</span></span>${icon('arrow')}</a><div class="hero-stats"><div><strong>60<span>+</span></strong><span>Projects</span></div><div><strong>8<span>+</span></strong><span>Companies</span></div><div><strong>15<span>+</span></strong><span>Platforms &amp; tools</span></div></div></div></section>

<div class="trusted-strip wrap"><p>Experience alongside</p><div><span>WINGMAN</span><span class="logo-serif">Auto Nurture</span><span class="logo-condensed">TOP LION<br><small>MARKETING</small></span><span class="logo-italic">speedy.ai</span><span class="logo-condensed">REMOTE CLEAN<br><small>ACADEMY</small></span></div></div>

<section class="expertise-section pad wrap" id="expertise" aria-labelledby="expertise-title"><div class="section-heading reveal"><div><p class="eyebrow">Connect the dots</p><h2 id="expertise-title">Three disciplines.<br><em>One better business.</em></h2></div><p>The front end people see. The systems they don’t. I bring both sides of the journey together.</p></div><div class="expertise-grid">${services.map((s,i)=>`<article class="expertise-card expertise-${s.color} ${i===0?'featured':''} reveal"><div class="expertise-card-top"><span class="card-discipline">${esc(s.short)}</span>${icon(s.icon)}</div><div class="expertise-card-inner"><div class="expertise-copy"><h3>${esc(s.homeTitle)}</h3><p>${esc(s.homeCopy)}</p><ul class="tags">${s.tags.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><a class="service-link" href="/${s.slug}/"><span>${i===0?'Explore GoHighLevel services':i===1?'Explore automation services':'Explore funnel services'}</span>${icon('arrow')}</a></div><div class="expertise-visual">${serviceVisual(s.short)}<span class="diagram-caption">Illustrative example</span></div></div></article>`).join('')}</div>
<div class="specialties reveal"><div class="specialties-head"><h3>Specific problems, focused help.</h3><p>Some projects need a specialist more than a general service. These are the areas I focus on.</p></div><ul class="specialties-list">${specialties.map(s=>`<li><a class="specialty spec-${s.color}" href="/${s.slug}/"><span class="specialty-icon">${icon(s.icon)}</span><span class="specialty-text"><strong>${esc(navLabel[s.slug])}</strong><span>${esc(s.homeCopy)}</span></span>${icon('arrow','specialty-arrow')}</a></li>`).join('')}</ul></div>
<div class="also-build reveal"><p>And the pieces in between</p><div><span>Email &amp; SMS</span><span>Memberships &amp; courses</span><span>Reporting &amp; analytics</span><span>Chatbots &amp; booking</span><span>Typeform &amp; Google Sheets</span></div></div></section>

<div class="band-wrap" aria-hidden="true"><div class="kinetic-band"><div class="band-track"><span>LESS FRICTION <b>✳</b> <em>more flow.</em> <b>✳</b> BETTER SYSTEMS <b>✳</b> <em>more possibility.</em> <b>✳</b></span><span>LESS FRICTION <b>✳</b> <em>more flow.</em> <b>✳</b> BETTER SYSTEMS <b>✳</b> <em>more possibility.</em> <b>✳</b></span></div></div></div>

<section class="experience-section wrap pad" id="experience" aria-labelledby="experience-title"><div class="experience-intro reveal"><p class="eyebrow">The work behind the work</p><h2 id="experience-title">Real teams.<br>Real systems.<br><em>Hands-on.</em></h2><p>From the first account setup to the backend that keeps things moving. Here’s where I’ve put the work in.</p><div class="experience-seal" aria-hidden="true"><span>✳</span><p>Thought through.<br>Connected with care.</p></div></div><div class="experience-list">${companies.map(([name,role,tags],i)=>`<details class="experience-item reveal" ${i===0?'open':''}><summary><span class="experience-number">${i+1}</span><span class="experience-company">${esc(name)}<small>${esc(role)}</small></span><span class="plus" aria-hidden="true">+</span></summary><div class="experience-body"><ul class="tags">${tags.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></div></details>`).join('')}</div></section>

<section class="process-section pad" id="process" aria-labelledby="process-title"><div class="wrap"><div class="section-heading reveal"><div><p class="eyebrow">No guesswork</p><h2 id="process-title">A little structure.<br><em>A lot of clarity.</em></h2></div><p>You’ll know what we’re building, why it matters and what comes next.</p></div><div class="process-layout"><div class="process-side" aria-hidden="true"><span class="process-orbit"></span><span class="process-glyph">✳</span><span class="process-side-copy">Good work<br>has a rhythm.</span></div><ol class="process-list">${processSteps.map(([verb,title,desc,time],i)=>`<li class="process-step reveal"><span class="process-number">${i+1}</span><div><span class="step-verb">${verb}</span><h3>${esc(title)}</h3><p>${esc(desc)}</p><small>${esc(time)}</small></div></li>`).join('')}</ol></div></div></section>

<section class="about-section pad" id="about" aria-labelledby="about-title"><div class="wrap about-layout"><div class="about-portrait reveal"><div class="portrait-topline"><span>The person behind the systems</span></div><div class="portrait-frame"><img src="/assets/hanzla-photo.jpg" width="672" height="830" loading="lazy" decoding="async" alt="Hanzla Amjad, GoHighLevel and marketing automation specialist based in Mian Channu, Pakistan"></div><div class="portrait-signature">Hanzla Amjad<span>GHL &amp; automation specialist</span></div></div><div class="about-copy reveal"><p class="eyebrow">Hi, I’m Hanzla</p><h2 id="about-title">I like the details<br>that make things<br><em>feel effortless.</em></h2><p>I’m a GoHighLevel specialist based in Mian Channu, Pakistan. I help agencies and businesses turn their funnels, customer data and marketing tools into a connected system.</p><p>A cleaner handoff. A timely follow-up. A workflow that takes something off your plate. That’s the kind of work I care about, and I’m available to businesses and agencies in Pakistan, the United States and the United Kingdom.</p><div class="about-facts"><div><span>Always learning</span><strong>BS Data Science</strong><p>2024–present · ICS, 2023</p></div><div><span>Let’s talk</span><strong>English &amp; Urdu</strong><p>Proficient · Native</p></div></div>${button('Tell me about your business','/#contact','button-dark')}</div></div><div class="wrap toolkit"><div><p class="eyebrow">My everyday toolkit</p><h3>The right tools.<br><em>Working together.</em></h3></div><div class="toolkit-groups"><div><h4>CRM &amp; collaboration</h4><p>GoHighLevel · ActiveCampaign · HubSpot · Mailchimp · ClickUp · Monday · Asana · Slack</p></div><div><h4>Automation &amp; integrations</h4><p>Zapier · Make · n8n · Webhooks · Twilio · Mailgun · Stripe · QuickBooks · Booking Kola · Typeform · Google Sheets · AI chatbots</p></div><div><h4>Design &amp; delivery</h4><p>Figma · Canva · Photopea · Project management · Clear communication</p></div></div></div></section>
${faq(homeFaqs)}
${contact(context)}`;}
