import {allPages} from './content.mjs';
import {escapeHtml as esc,button,icon,faq,navLabel} from './layout.mjs';

export function serviceBody(s) {
  const contactHref=`/?service=${encodeURIComponent(s.subject)}#contact`;
  const related=(s.related||[]).map(slug=>allPages.find(p=>p.slug===slug)).filter(Boolean);
  return `<section class="service-hero wrap"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><span aria-current="page">${esc(s.short)}</span></nav><div class="service-hero-grid"><div><h1>${esc(s.heading)} <em>${esc(s.accent)}</em></h1><p class="service-hero-description">${esc(s.intro)}</p>${button('Talk about your project',contactHref)}</div><div class="service-hero-mark mark-${s.color}" aria-hidden="true">${icon(s.icon)}</div></div><ul class="service-hero-tags">${s.tags.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></section>
  <section class="service-fit wrap pad"><p class="eyebrow">Where we start</p><div><h2>${esc(s.fitTitle)}</h2><p>${esc(s.fit)}</p><p>${esc(s.fitMore)}</p></div></section>
  <section class="deliverables-section pad"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">The build, made clear</p><h2>What we can<br><em>put in place.</em></h2></div><p>Your final scope is agreed around your account, tools and goals.</p></div><div class="deliverables-grid">${s.deliverables.map(([title,desc])=>`<article class="deliverable reveal"><h3>${esc(title)}</h3><p>${esc(desc)}</p></article>`).join('')}</div></div></section>
  <section class="service-approach wrap pad"><div><p class="eyebrow">The approach</p><h2>A clear route<br>to <em>working better.</em></h2><p class="approach-experience">${esc(s.experience)}</p><a class="quiet-link" href="/#experience"><span>See my experience</span>${icon('arrow')}</a></div><ol>${s.approach.map(([title,desc],i)=>`<li><span>${i+1}</span><div><h3>${esc(title)}</h3><p>${esc(desc)}</p></div></li>`).join('')}</ol></section>
  <aside class="scope-note wrap"><span>${icon('check')}</span><div><h2>Clear scope. Shared expectations.</h2><p>${esc(s.expectations)}</p></div></aside>
  ${faq(s.faq,`${esc(s.short)} questions,<br><em>answered.</em>`)}
  <section class="service-next pad"><div class="wrap"><p class="eyebrow">Let’s talk about your next step</p><h2>Make your system<br><em>work for you.</em></h2><p>Tell me what you’re working with and what you’d like to change.</p>${button('Start a conversation',contactHref)}</div></section>
  <nav class="related-services wrap" aria-label="Related services"><p>Connect the rest of your journey</p><div>${related.map(other=>`<a href="/${other.slug}/"><span>${esc(navLabel[other.slug])}</span>${icon('arrow')}</a>`).join('')}</div></nav>`;
}

export function privacyBody() {
 return `<article class="legal-page wrap pad"><p class="eyebrow">A note on your details</p><h1>Privacy, <em>plainly.</em></h1><p>This page explains how this portfolio handles the information you choose to share.</p><h2>Project inquiries</h2><p>The contact form asks for your name, email address, project type, a message and an optional WhatsApp number. These details are used to review and respond to your inquiry. The form sends your submission through Web3Forms, the existing contact provider used by this portfolio.</p><h2>Direct contact</h2><p>Email, phone and WhatsApp links open the relevant service. If you choose one of these, that service’s own privacy practices apply. Your contact information is not included in the portfolio’s interaction-event data.</p><h2>Browser storage</h2><p>Campaign parameters, when present in a link, can be retained in session storage for the current browser tab and included with your inquiry. Your name, email, phone number and message are not stored in browser storage by this site.</p><h2>Measurement and hosting</h2><p>This version includes no third-party advertising pixel or analytics script, and its fonts are served from the site itself. It prepares local interaction events for future measurement, without contact-field contents. Hosting and contact providers may process technical information needed to operate their services. This notice should be updated if additional measurement tools are installed.</p><h2>Questions about your information</h2><p>Contact Hanzla Amjad at <a href="mailto:hanzala.ghl@gmail.com">hanzala.ghl@gmail.com</a> with questions about an inquiry or a request concerning information you have shared.</p>${button('Back to the portfolio','/','button-outline')}</article>`;
}
